=== wladimiiir/sodalis/core/src/main/resources/sk/magiksoft/sodalis/core/filter/ColumnComponents.dtd
<?xml version='1.0' encoding='UTF-8'?>

        <!--
            TODO define vocabulary identification
            PUBLIC ID: -//vendor//vocabulary//EN
            SYSTEM ID: http://server/path/ColumnComponents.dtd

        --><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

    <ColumnComponents>
    ...
    </ColumnComponents>
-->

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT ColumnComponents (ColumnComponent)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT ColumnComponent (label_text, select?, from, where, items?)>
        <!ATTLIST ColumnComponent
                class CDATA #IMPLIED
                >

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT label_text (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT select (#PCDATA)>

        <!ELEMENT from (#PCDATA)>
        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT where (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT items (item)*>
        <!ATTLIST items
                enumeration CDATA #IMPLIED
                enumclass CDATA #IMPLIED
                >

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT item (#PCDATA)>

=== wladimiiir/sodalis/data/filter/InventoryFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

<ColumnComponents>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Evidenčné čislo</label_text>
        <select>ii</select>
        <from>sk.magiksoft.sodalis.folkensemble.inventory.entity.InventoryItem ii,
            sk.magiksoft.sodalis.item.entity.ItemPropertyValue ipv, sk.magiksoft.sodalis.item.entity.ItemProperty ip
        </from>
        <where>ipv in elements(ii.values) and ''EvidenceNumber'' in elements(ip.propertyTypes) and
            ip.id=ipv.itemPropertyID and upper(remove_diacritics(deserialize_string(ipv.value))) {0} {1}
        </where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Popis</label_text>
        <select>ii</select>
        <from>sk.magiksoft.sodalis.folkensemble.inventory.entity.InventoryItem ii,
            sk.magiksoft.sodalis.item.entity.ItemPropertyValue ipv, sk.magiksoft.sodalis.item.entity.ItemProperty ip
        </from>
        <where>ipv in elements(ii.values) and ip.id=ipv.itemPropertyID and
            upper(remove_diacritics(deserialize_string(ipv.value))) {0} {1}
        </where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.MultiselectComboboxColumnComponent">
        <label_text>Stav</label_text>
        <select>ii</select>
        <from>InventoryItem ii, BorrowingInventoryItemData biid</from>
        <where>biid in elements(ii.inventoryItemDatas) AND biid.state {0} {1}</where>
        <items enumclass="sk.magiksoft.sodalis.folkensemble.inventory.entity.BorrowingInventoryItemData$InventoryItemState"/>
    </ColumnComponent>
</ColumnComponents>

=== wladimiiir/sodalis/data/filter/RepertoryFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

<ColumnComponents>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Názov</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.repertory.entity.Song s</from>
        <where>upper(remove_diacritics(s.name)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Popis</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.repertory.entity.Song s</from>
        <where>upper(remove_diacritics(s.description)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.EditableMultiselectComboboxColumnComponent">
        <label_text>Žáner</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.repertory.entity.Song s</from>
        <where>upper(remove_diacritics(s.genre)) {0} {1}</where>
        <items enumeration="SongGenre"/>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.EditableMultiselectComboboxColumnComponent">
        <label_text>Región</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.repertory.entity.Song s</from>
        <where>upper(remove_diacritics(s.region)) {0} {1}</where>
        <items enumeration="FolkRegion"/>
    </ColumnComponent>
</ColumnComponents>

=== wladimiiir/sodalis/data/filter/MemberColumnComponents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

<!--
    Document   : MemberColumnComponents.xml
    Created on : Nedeľa, 2008, júl 20, 17:26
    Author     : wladimiiir
    Description:
        Purpose of the document follows.
-->

<ColumnComponents>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.SearchFromStartTextFieldColumnComponent">
        <label_text>Meno, priezvisko</label_text>
        <from>sk.magiksoft.sodalis.person.entity.Person p</from>
        <where>upper(remove_diacritics(p.firstName)) {0} {1} OR upper(remove_diacritics(p.lastName)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.DateColumnComponent">
        <label_text>Dátum narodenia</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p, sk.magiksoft.sodalis.person.entity.PrivatePersonData ppd
        </from>
        <where>ppd in elements(p.personDatas) AND ppd.birthDate {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Adresa</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p, sk.magiksoft.sodalis.person.entity.PrivatePersonData ppd
        </from>
        <where>ppd in elements(p.personDatas) AND (upper(remove_diacritics(ppd.address.street)) {0} {1} OR
            ppd.address.number {0} {1} OR upper(remove_diacritics(ppd.address.town)) {0} {1} OR ppd.address.postcode {0}
            {1} OR upper(remove_diacritics(ppd.address.state)) {0} {1})
        </where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.MultiselectComboboxColumnComponent">
        <label_text>Pohlavie</label_text>
        <from>sk.magiksoft.sodalis.person.entity.Person p</from>
        <where>p.sex {0} {1}</where>
        <items enumclass="sk.magiksoft.sodalis.person.entity.Person$Sex"/>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Akademické údaje</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p,
            sk.magiksoft.sodalis.folkensemble.member.entity.UniversityData ud
        </from>
        <where>ud in elements(p.personDatas) AND (upper(remove_diacritics(ud.university)) {0} {1} OR
            upper(remove_diacritics(ud.faculty)) {0} {1} OR upper(remove_diacritics(ud.department)) {0} {1} OR
            upper(remove_diacritics(ud.specialization)) {0} {1})
        </where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.MultiselectComboboxColumnComponent">
        <label_text>Typ štúdia</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p,
            sk.magiksoft.sodalis.folkensemble.member.entity.UniversityData ud
        </from>
        <where>ud in elements(p.personDatas) AND ud.studiumType {0} {1}</where>
        <items enumeration="UniversityStudiumType"/>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.MultiselectComboboxColumnComponent">
        <label_text>Ročník</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p,
            sk.magiksoft.sodalis.folkensemble.member.entity.UniversityData ud
        </from>
        <where>ud in elements(p.personDatas) AND ud.year {0} {1}</where>
        <items>
            <item>1</item>
            <item>2</item>
            <item>3</item>
            <item>4</item>
            <item>5</item>
            <item>6</item>
        </items>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.folkensemble.member.filter.EnsembleGroupColumnComponent">
        <label_text>Zložka</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p, sk.magiksoft.sodalis.folkensemble.member.entity.EnsembleData
            ed
        </from>
        <where>ed.ensembleGroup.groupType</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.MultiselectComboboxColumnComponent">
        <label_text>Stav člena</label_text>
        <select>p</select>
        <from>sk.magiksoft.sodalis.person.entity.Person p, sk.magiksoft.sodalis.folkensemble.member.entity.MemberData md
        </from>
        <where>md in elements(p.personDatas) AND md.status {0} {1}</where>
        <items enumclass="sk.magiksoft.sodalis.folkensemble.member.entity.MemberData$MemberStatus"/>
    </ColumnComponent>
</ColumnComponents>

=== wladimiiir/sodalis/data/filter/ProgrammeFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

<ColumnComponents>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>NÃ¡zov</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.programme.entity.Programme p</from>
        <where>upper(remove_diacritics(p.name)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Popis</label_text>
        <from>sk.magiksoft.sodalis.folkensemble.programme.entity.Programme p</from>
        <where>upper(remove_diacritics(p.description)) {0} {1}</where>
    </ColumnComponent>
</ColumnComponents>

=== wladimiiir/sodalis/data/filter/EventFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ColumnComponents SYSTEM "ColumnComponents.dtd">

<ColumnComponents>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.NoComparatorDateColumnComponent">
        <label_text>Od</label_text>
        <from>sk.magiksoft.sodalis.event.entity.Event e</from>
        <where><![CDATA[e.startTime >= {0} or (e.repeatMask<>0 and e.repeatStart >= {0})]]></where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.NoComparatorDateColumnComponent">
        <label_text>Do</label_text>
        <from>sk.magiksoft.sodalis.event.entity.Event e</from>
        <where>
            <![CDATA[DATEADD(''DAY'',-1,e.endTime) <= {0} or (e.repeatMask<>0 and DATEADD(''DAY'',1,e.repeatEnd) <= {0})]]></where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>NÃ¡zov udalosti</label_text>
        <from>sk.magiksoft.sodalis.event.entity.Event e</from>
        <where>upper(remove_diacritics(e.eventName)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.core.filter.element.TextFieldColumnComponent">
        <label_text>Miesto</label_text>
        <from>sk.magiksoft.sodalis.event.entity.Event e</from>
        <where>upper(remove_diacritics(e.place)) {0} {1}</where>
    </ColumnComponent>
    <ColumnComponent class="sk.magiksoft.sodalis.event.filter.EventTypeColumnComponent">
        <label_text>Typ udalosti</label_text>
        <from>sk.magiksoft.sodalis.event.entity.Event e</from>
        <where>e.eventType.id {0} {1}</where>
    </ColumnComponent>
</ColumnComponents>
